baseurl = "https://www.omgcommunity.network/"
title = "Deplebify"
theme = "hugo-theme-console"
languageCode = "en-us"

[params]
  # Cutting off the page title to two chars for mobile (console-demo -> co)
  titleCutting = false

  [[params.navlinks]]
  name = "posts/"
  url = "posts/"
  
  [[params.navlinks]]
  name = "Network/"
  url = "omgnetwork/"

  [[params.navlinks]]
  name = "Price/"
  url = "price/"

  [[params.navlinks]]
  name = "Deposits/"
  url = "deposit/"