baseurl = "https://www.omgcommunity.network/"
title = "Deplebify"
theme = "hugo-theme-console"
languageCode = "en-us"

[params]
  # Cutting off the page title to two chars for mobile (console-demo -> co)
  titleCutting = true

  [[params.navlinks]]
  name = "about/"
  url = "about/"

  [[params.navlinks]]
  name = "posts/"
  url = "posts/"
  
  [[params.navlinks]]
  name = "OMGNetwork/"
  url = "omgnetwork/"

  [[params.navlinks]]
  name = "Price/"
  url = "price/"

  [[params.navlinks]]
  name = "Deposits/"
  url = "deposit/"

  [[params.navlinks]]
  name = "Rankings/"
  url = "rankings/"