baseURL = "https://icy-bay-0b0640403.azurestaticapps.net/"
title = "Deplebify"
languageCode = "en"
DefaultContentLanguage = "en" # Change this to change the site's language
theme = "hugo.386"
preserveTaxonomyNames = true
enableEmoji = true

[params]
    # The name to display as main title in the home page
    mainpagetitle = "Deplebify"

    # The subtitle to display under the title in the home page
    mainpagesubtitle = "Can you read me now?"

    # The description of your website. It will be displayed in the home page
    mainpagedesc = "This theme should make the old buffers happy"

    # The name to display in the copyright section in the footer
    copyrightname = "The Pickler"

    # The url to use as link in the copyright name in the footer. Leave empty to use none.
    copyrighturl = ""

    # Show the "built on Hugo" disclaimer
    # showhugo = true

    # Urls for social networks
    # facebook = "https://facebook.com"
    # twitter = "https://twitter.com"
    # linkedin = "https://linkedin.com"
    # github = "https://github.com"
    # gitlab = "https://gitlab.com"

    # Enables or disables the loading animations. false activates them. Default is false.
    loadfastload = false

    # Sets the speed for the page loading effect. Default is 1.0.
    loadspeedfactor = 1.0

    # Enables or disables the second flyby cursor. Default is false.
    loadonepass = false

[params.copyright]
    name = "PickledNewtons"

    # The url to use as link in the copyright name in the footer. Leave empty to use none.
    url = "https://www.google.com/search?q=pickle&source=lnms&tbm=isch&sa=X&ved=2ahUKEwj0lMHu34brAhXfUhUIHfVqDxUQ_AUoAXoECBYQAw&biw=1920&bih=920"

    # Text to go before copyright information
    prefix = "OMG Network test site"

    # Text to go between copyright and hugo disclaimer (if enabled)
    suffix = ""

[menu]
  # This displays buttons in the navbar to access your contents
  [[menu.main]]
    identifier = "about" # An unique identifier for the button
    name = "About"       # A display name for the button
    url = "/about/"      # The path to the content. It can lead to a single page (like here)
    weight = 10          # A number to order the buttons in the navbar

  [[menu.main]]
    identifier = "OMGNetwork" # An unique identifier for the button
    name = "OMGNetwork"       # A display name for the button
    url = "/OMGNetwork/"      # The path to the content. It can lead to a single page (like here)
    weight = 10  

  [[menu.main]]
    identifier = "OMGPrice" # An unique identifier for the button
    name = "OMGPrice"       # A display name for the button
    url = "/price/"      # The path to the content. It can lead to a single page (like here)
    weight = 10  

  [[menu.main]]
    identifier = "posts"
    name = "All posts"
    url = "/post"       # The path can lead to a content folder too.
    weight = 20

[taxonomies]
category = "categories"
tag = "tags"


[privacy]

  [privacy.vimeo]
    disabled = false
    simple = true

  [privacy.twitter]
    disabled = false
    enableDNT = true
    simple = true

  [privacy.instagram]
    disabled = false
    simple = true

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[services]

  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true